version: '3'

services:
  app:
    container_name: currency-converter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9527:9527"
    volumes:
      - ./:/codes
    command: ["pytest", "-v"]
    entrypoint: ["python", "main.py"]